version: '3.7'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - global
    command: python main.py
    deploy:
        resources:
            limits:
              cpus: '2.50'
              memory: 10240M
            reservations:
              cpus: '0.80'
              memory: 5120M  
  
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    
networks:
  global:
    driver: bridge
